{
 "title": "pgSCV",
 "description": "PostgreSQL dashboard for pgSCV metrics (Prometheus version, pgSCV 0.7.0 edition)",
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(node_load1{job='postgres'}, service) "
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(node_load1{job='postgres'}, env) "
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_boot_time_seconds{job='pgscv', env=~\"$env\",service=~\"$service\"}, instance)"
    }
   },
   {
    "name": "postgres",
    "query": {
     "query": "label_values(pgscv_services_registered_total, service_id)"
    }
   },
   {
    "name": "server_ip",
    "query": {
     "query": "label_values(node_load1{job='pgscv', env=~\"$env\",instance=\"$instance\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Main",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "group(node_uname_info{job=\"postgres\",env=~\"$env\",service=~\"$service\"}) by (nodename,instance,server_ip,env,service)"
    },
    {
     "expr": "time()-node_boot_time_seconds{ job=\"postgres\",env=~\"$env\",service=~\"$service\"}"
    },
    {
     "expr": "count (node_cpu_seconds_total{mode=\"idle\", job=\"postgres\", env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "100 - (avg by (instance) ((irate(node_cpu_seconds_total{job=\"postgres\",mode=\"idle\",env=~\"$env\",service=~\"$service\"}[2m])))* 100)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (node_memory_MemTotal_bytes{job='postgres',env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "100- 100*sum(node_memory_MemAvailable_bytes{job=\"postgres\", env=~\"$env\",service=~\"$service\"}/node_memory_MemTotal_bytes{job=\"postgres\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job='postgres', mountpoint='/', env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "100 - 100 *sum(node_filesystem_free_bytes{job='postgres',mountpoint='/',env=~\"$env\",service=~\"$service\"}/node_filesystem_size_bytes{job='postgres',mountpoint='/',env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job='postgres',mountpoint='/var/lib/postgresql',env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "100 - 100 * sum(node_filesystem_free_bytes{job='postgres', mountpoint='/var/lib/postgresql', env=~\"$env\",service=~\"$service\"}/node_filesystem_size_bytes{job='postgres', mountpoint='/var/lib/postgresql', env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job='postgres', mountpoint='/var/lib/postgresql', env=~\"$env\",service=~\"$service\"} - node_filesystem_free_bytes {job='postgres', mountpoint='/var/lib/postgresql',env=~\"$env\",service=~\"$service\"})\r\nby (instance)"
    },
    {
     "expr": "count(node_systemd_unit_state{job=\"postgres\",name=\"patroni.service\",state=\"active\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "count(node_systemd_unit_state{job=\"postgres\",name=\"etcd.service\",state=\"active\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "count(node_systemd_unit_state{job=\"postgres\",name=\"keepalived.service\",state=\"active\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "count(node_systemd_unit_state{job=\"postgres\",name=\"haproxy.service\",state=\"active\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    },
    {
     "expr": "count(node_systemd_unit_state{job=\"postgres\",name=\"pgscv.service\",state=\"active\",env=~\"$env\",service=~\"$service\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Current status of PostgreSQL service.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_up{instance=\"$instance\",service_id=\"$postgres\", job=\"pgscv\"}",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of log messages rate (per minute) with severity higher than LOG (e.g. WARNING, ERROR, FATAL and PANIC).",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(postgres_log_messages_total{level!=\"log\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Longest Activity",
   "type": "stat",
   "description": "Current longest transaction activity, initiated by clients or background service (e.g. autovacuum).",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Patroni",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (server_ip) (patroni_master{env=~\"$env\",service=~\"$service\",job=\"patroni\"})"
    },
    {
     "expr": "sum by (server_ip) (patroni_replica{env=~\"$env\",service=~\"$service\",job=\"patroni\"})"
    },
    {
     "expr": "sum by (server_ip)(patroni_pending_restart{job=\"patroni\",env=~\"$env\",service=~\"$service\"})"
    },
    {
     "expr": "sum by (server_ip)(patroni_postgres_timeline{job=\"patroni\",env=~\"$env\",service=~\"$service\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (server_ip) (patroni_postmaster_start_time{job=\"patroni\",env=~\"$env\",service=~\"$service\"}*1000)"
    },
    {
     "expr": "sum(label_replace(\r\n  postgres_replication_lag_all_bytes{env=~\"$env\",service=~\"$service\",job=\"pgscv\"}, \"server_ip\", \"$1\", \"client_addr\", \"(.*)/(.*)\"\r\n)) by (server_ip)"
    },
    {
     "expr": "sum(label_replace(\r\n  postgres_replication_lag_all_seconds{env=~\"$env\",service=~\"$service\",job=\"pgscv\"}, \"server_ip\", \"$1\", \"client_addr\", \"(.*)/(.*)\"\r\n)) by (server_ip)"
    },
    {
     "expr": "sum(label_replace(\r\n  patroni_postgres_running{env=~\"$env\",service=~\"$service\",job=\"pgscv\"}, \"server_ip\", \"$1\", \"client_addr\", \"(.*)/(.*)\"\r\n)) by (server_ip)"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "description": "Total number of connected clients.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Response Time, avg",
   "type": "stat",
   "description": "Average response time calculated using time of executed statements.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) / sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "response time"
    }
   ]
  },
  {
   "title": "Statements",
   "type": "stat",
   "description": "Rate of successfully executed statements per second.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
     "legendFormat": "statements"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Client Activity",
     "type": "graph",
     "description": "Query activity produced by connected clients.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "statements"
      },
      {
       "expr": "sum(rate(postgres_database_xact_commits_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "commits"
      },
      {
       "expr": "sum(rate(postgres_database_xact_rollbacks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "rollbacks"
      }
     ]
    },
    {
     "title": "Client Connections",
     "type": "graph",
     "description": "States of connections established by clients (doesn't include states of background services).",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_activity_connections_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Longest Activity",
     "type": "timeseries",
     "description": "The most longest activity produced by connected clients and background services.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, max by (user) (postgres_activity_max_seconds{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{user}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements (pg_stat_statements required)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Calls",
     "type": "graph",
     "description": "The top-most executed statements.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_calls_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Rows",
     "type": "graph",
     "description": "The top-most statements by returned rows.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_rows_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "Total time",
     "type": "graph",
     "description": "The top-most statements by total time (planning, executing and doing IO).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, (rate(postgres_statements_time_seconds_all_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    },
    {
     "title": "IO time",
     "type": "graph",
     "description": "The top-most statements by IO time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum without (mode) (rate(postgres_statements_time_seconds_total{mode=~\"ioread|iowrite\",instance=\"$instance\",service_id=\"$postgres\"}[1m])) + on(database,user,queryid) group_left(query) (0 * postgres_statements_query_info{instance=\"$instance\",service_id=\"$postgres\"}))",
       "legendFormat": "{{database}}/{{user}}/{{query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks and Wait Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wait Events, by type",
     "type": "graph",
     "description": "Wait events aggregated by type.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Wait Events",
     "type": "graph",
     "description": "The top-most wait events occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_activity_wait_events_in_flight{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ type }}:{{ event }}"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "graph",
     "description": "Total number of locks acquired.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_locks_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Deadlocks, per minute",
     "type": "graph",
     "description": "Total number of deadlocks per minute.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(postgres_database_deadlocks_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "deadlocks"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replication Lag, bytes",
     "type": "graph",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    },
    {
     "title": "Replication Lag, seconds",
     "type": "graph",
     "description": "Total amount of replication lag, when standbys left behind the master.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (client_addr) (postgres_replication_lag_all_seconds{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ client_addr }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WAL write, bytes per second",
   "type": "graph",
   "description": "Amount of WAL generated or received by Postgres instance.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "WAL directory size",
   "type": "graph",
   "description": "Total size of WAL directory, in bytes.",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "WAL settings",
   "type": "table",
   "description": "WAL settings",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"(max|min)_wal_size|max_slot_wal_keep_size|full_page_writes|wal_keep_(size|segments)|wal_(compression|level|log_hints)\"})"
    }
   ]
  },
  {
   "title": "Vacuum Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Vacuums",
     "type": "graph",
     "description": "Total number of automatic and user-initiated vacuum operations.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_activity_vacuums_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Vacuumed tables, per-minute",
     "type": "graph",
     "description": "The top-most vacuumed tables.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(postgres_table_maintenance_total{type=\"autovacuum\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ table }}"
      }
     ]
    },
    {
     "title": "Autovacuum settings",
     "type": "table",
     "description": "Autovacuum settings.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"^(auto)?vacuum.+\"})"
      }
     ]
    },
    {
     "title": "Transactions left before wraparound",
     "type": "graph",
     "description": "Total number transactions left before XID wraparound occurs.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "postgres_xacts_left_before_wraparound{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ xid_from }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Checkpoints",
     "type": "graph",
     "description": "Total number of checkpoints occurred.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(postgres_checkpoints_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ checkpoint }}"
      }
     ]
    },
    {
     "title": "Background Writes",
     "type": "graph",
     "description": "Total writes performed by background services or by backends implicitly.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(postgres_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "{{ process }}"
      },
      {
       "expr": "rate(postgres_wal_written_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "wal"
      },
      {
       "expr": "sum(rate(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "tempfiles"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "graph",
     "description": "Disk space usage by Postgres instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_tablespace_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      },
      {
       "expr": "postgres_wal_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "wal"
      },
      {
       "expr": "postgres_log_directory_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "log"
      }
     ]
    },
    {
     "title": "Databases",
     "type": "graph",
     "description": "Top databases by size.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_database_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Tables",
     "type": "graph",
     "description": "Top tables by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_table_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}"
      }
     ]
    },
    {
     "title": "Indexes",
     "type": "graph",
     "description": "Top indexes by size in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_index_size_bytes{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{ database }}.{{ schema }}.{{ table }}.{{ index }}"
      }
     ]
    },
    {
     "title": "Databases Temporary Files",
     "type": "graph",
     "description": "Top databases by produced temporary files in bytes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "topk(5, increase(postgres_database_temp_bytes_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{ database }}"
      }
     ]
    },
    {
     "title": "Temporary Files in-flight",
     "type": "graph",
     "description": "Total size of active temporary files in-flight.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_temp_bytes_in_flight{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "{{ tablespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sequential Read, by rows",
     "type": "graph",
     "description": "The top-most tables which accessed sequentially.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_seq_tup_read_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "Dead Tuples",
     "type": "graph",
     "description": "The top-most tables with dead tuples.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, postgres_table_tuples_dead_total{instance=\"$instance\",service_id=\"$postgres\"})",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "INSERTs",
     "type": "graph",
     "description": "The top-most tables with performed INSERTs per second.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_inserted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "UPDATEs",
     "type": "graph",
     "description": "The top-most tables with performed UPDATEs (including HOT) per second.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_updated_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    },
    {
     "title": "DELETEs",
     "type": "graph",
     "description": "The top-most tables with performed DELETEs per second.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(postgres_table_tuples_deleted_total{instance=\"$instance\",service_id=\"$postgres\"}[1m]))",
       "legendFormat": "{{schema}}.{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL Archiving",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "WAL Archiving Lag, bytes",
     "type": "graph",
     "description": "Total amount of WAL segments (in bytes) which are not archived yet.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "postgres_archiver_lag_bytes{instance=\"$instance\",service_id=\"$postgres\"}",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "WAL Archiving, per minute",
     "type": "graph",
     "description": "Total amount of WAL segments processed per minute.",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "increase(postgres_archiver_archived_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "archived"
      },
      {
       "expr": "increase(postgres_archiver_failed_total{instance=\"$instance\",service_id=\"$postgres\"}[1m])",
       "legendFormat": "failed"
      }
     ]
    },
    {
     "title": "WAL archiving settings",
     "type": "table",
     "description": "Important: when WAL archiving is disabled, metrics will not be collected.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"archive_.+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "System Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=\"$instance\"}[1m])) / on (instance) group_left sum(rate(node_cpu_seconds_all_total{instance=\"$instance\"}[1m]))",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Storage Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum by (device) (rate(node_disk_time_seconds_total{instance=\"$instance\"}[1m])) / (sum by (device) (rate(node_disk_completed_total{instance=\"$instance\"}[1m])) + on() group_left vector(1))",
       "legendFormat": "{{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log messages, per minute",
   "type": "timeseries",
   "description": "Messages written to log, by severity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(postgres_log_messages_total{level!=\"log\",instance=\"$instance\",service_id=\"$postgres\"}[1m]))"
    }
   ]
  },
  {
   "title": "Logging settings",
   "type": "table",
   "description": "Important: when logging_collector is disabled, log metrics will not be collected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name,setting) (postgres_service_settings_info{instance=\"$instance\",service_id=\"$postgres\",name=~\"logging_collector|log_directory|log_filename\"})"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "{service=~\"$service\",env=~\"$env\"}"
    }
   ]
  }
 ]
}